### ISSUE TITLE
my own messages

### ISSUE THREAD

**Issue by xhava** [laracasts/Validation#2]
how can i create my own messages . thanks

**Comment by laracasts** [comment]
Add a `messages` property on your form object.

``` php
protected $messages = [
    'required' => 'Yo, that was needed, man.'
];
```

**Comment by xhava** [comment]
thanks @JeffreyWay  but it does not work for me. 

i have the next

<?php namespace CarteroElectronico\Forms;

use Laracasts\Validation\FormValidator;

class LoginForm extends FormValidator {

```
protected $rules = [

    'email_login' => 'required',
    'password_login' => 'required'

];

protected $messages = [

'required' => 'este campo es obligatorio'

];
```

}

**Comment by laracasts** [comment]
Can you try doing composer update?

**Comment by xhava** [comment]
thanks @JeffreyWay  that worked for me.
